"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import {
  summarizeCounts,
  type RecommendationCounts,
  type SchemaRecommendation,
  type Explanation,
} from "@/lib/meta-model";
import type { EditableCategory } from "@/lib/recommendation-edit";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { CornerTicks, DimensionRule } from "@/components/construction-marks";
import {
  approveAndGenerate,
  regenerateRecommendation,
  removeRecommendationItem,
  renameRecommendationItem,
} from "./actions";

interface Item {
  key: string;
  name: string;
  meta?: string;
  explanation: Explanation;
}

export function ReviewClient({
  orgId,
  orgName,
  recommendation,
  counts,
  source,
  canApprove,
}: {
  orgId: string;
  orgName: string;
  recommendation: SchemaRecommendation;
  counts: RecommendationCounts;
  source: string;
  canApprove: boolean;
}) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  function run(fn: () => Promise<{ error?: string }>) {
    setError(null);
    startTransition(async () => {
      try {
        const res = await fn();
        if (res?.error) setError(res.error);
        else router.refresh();
      } catch (e) {
        if ((e as { digest?: string })?.digest?.startsWith("NEXT_REDIRECT")) return;
        setError((e as Error).message || "Something went wrong.");
      }
    });
  }

  const rec = recommendation;

  return (
    <div className="space-y-8">
      <div>
        <p className="text-sm text-muted-foreground">Recommended operating model · {orgName}</p>
        <h1 className="mt-1 text-2xl font-semibold tracking-tight">
          Review &amp; approve your model
        </h1>
      </div>

      <Card className="relative">
        <CornerTicks />
        <CardContent className="space-y-5 pt-6">
          <p className="text-lg">{summarizeCounts(counts)}</p>
          <div className="flex flex-wrap gap-3">
            <CountChip n={counts.recordTypes} label="record types" />
            <CountChip n={counts.relationshipTypes} label="relationships" />
            <CountChip n={counts.permissionGroups} label="permission groups" />
            <CountChip n={counts.workflows} label="workflows" />
            <CountChip n={counts.dashboards} label="dashboards" />
            <CountChip n={counts.healthChecks} label="automated checks" />
            <CountChip n={counts.suggestedQuestions} label="suggested questions" />
            <CountChip n={counts.importMappings} label="import mappings" />
          </div>
          <DimensionRule />
          <div className="flex items-center gap-3 text-xs text-muted-foreground">
            <Badge variant={source === "openai" ? "accent" : "secondary"}>
              Generated by: {source}
            </Badge>
            <span>Counts are computed from the model below — nothing is hard-coded.</span>
          </div>
        </CardContent>
      </Card>

      {error ? (
        <p role="alert" className="rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">
          {error}
        </p>
      ) : null}

      <Section
        title="Record types"
        category="recordTypes"
        items={rec.recordTypes.map((r) => ({
          key: r.key,
          name: r.name,
          meta: `${r.fields?.length ?? 0} fields · ${r.sensitivity.toLowerCase()}`,
          explanation: r.explanation,
        }))}
        orgId={orgId}
        pending={pending}
        run={run}
        renamable
      />

      <Section
        title="Relationships"
        category="relationshipTypes"
        items={rec.relationshipTypes.map((r) => ({
          key: r.key,
          name: `${r.sourceTypeKey} — ${r.forwardLabel} → ${r.targetTypeKey}`,
          meta: r.cardinality.replace(/_/g, " "),
          explanation: r.explanation,
        }))}
        orgId={orgId}
        pending={pending}
        run={run}
      />

      <Section
        title="Permission groups"
        category="permissionGroups"
        items={rec.permissionGroups.map((g) => ({
          key: g.key,
          name: g.name + (g.isDefault ? " (default)" : ""),
          meta: `reads up to ${g.capabilities.maxReadSensitivity.toLowerCase()}`,
          explanation: g.explanation,
        }))}
        orgId={orgId}
        pending={pending}
        run={run}
        renamable
      />

      <Section
        title="Workflows"
        category="workflows"
        items={rec.workflows.map((w) => ({
          key: w.key,
          name: w.name,
          meta: w.states.map((s) => s.name).join(" → "),
          explanation: w.explanation,
        }))}
        orgId={orgId}
        pending={pending}
        run={run}
        renamable
      />

      <Section
        title="Dashboards"
        category="dashboards"
        items={rec.dashboards.map((d) => ({
          key: d.key,
          name: d.name,
          meta: `${d.widgets.length} widgets`,
          explanation: d.explanation,
        }))}
        orgId={orgId}
        pending={pending}
        run={run}
        renamable
      />

      <Section
        title="Automated health checks"
        category="healthChecks"
        items={rec.healthChecks.map((h) => ({
          key: h.key,
          name: h.name,
          meta: h.severity,
          explanation: h.explanation,
        }))}
        orgId={orgId}
        pending={pending}
        run={run}
        renamable
      />

      <DimensionRule />

      <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
        <Button
          variant="outline"
          disabled={pending}
          onClick={() => run(() => regenerateRecommendation(orgId))}
        >
          Regenerate from answers
        </Button>
        {canApprove ? (
          <Button
            disabled={pending}
            onClick={() => run(() => approveAndGenerate(orgId))}
          >
            {pending ? "Working…" : "Approve & generate workspace"}
          </Button>
        ) : (
          <p className="text-sm text-muted-foreground">
            Ask an administrator to approve and generate the workspace.
          </p>
        )}
      </div>
    </div>
  );
}

function CountChip({ n, label }: { n: number; label: string }) {
  return (
    <span className="inline-flex flex-col items-start border border-border px-3 py-1.5">
      <span className="font-mono text-lg font-semibold tabular-nums leading-none text-primary">
        {n}
      </span>
      <span className="mt-0.5 text-[10px] uppercase tracking-[0.08em] text-muted-foreground">
        {label}
      </span>
    </span>
  );
}

function Section({
  title,
  category,
  items,
  orgId,
  pending,
  run,
  renamable = false,
}: {
  title: string;
  category: EditableCategory;
  items: Item[];
  orgId: string;
  pending: boolean;
  run: (fn: () => Promise<{ error?: string }>) => void;
  renamable?: boolean;
}) {
  return (
    <section className="space-y-3">
      <div className="flex items-center gap-2">
        <h2 className="text-lg font-semibold">{title}</h2>
        <Badge variant="secondary">{items.length}</Badge>
      </div>
      <div className="space-y-2">
        {items.map((item) => (
          <ItemRow
            key={item.key}
            item={item}
            category={category}
            orgId={orgId}
            pending={pending}
            run={run}
            renamable={renamable}
          />
        ))}
      </div>
    </section>
  );
}

function ItemRow({
  item,
  category,
  orgId,
  pending,
  run,
  renamable,
}: {
  item: Item;
  category: EditableCategory;
  orgId: string;
  pending: boolean;
  run: (fn: () => Promise<{ error?: string }>) => void;
  renamable: boolean;
}) {
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(item.name);

  return (
    <Card>
      <CardContent className="flex items-start justify-between gap-4 py-4">
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            {editing ? (
              <Input
                autoFocus
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="h-8 max-w-xs"
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    setEditing(false);
                    run(() =>
                      renameRecommendationItem(orgId, category, item.key, name),
                    );
                  }
                  if (e.key === "Escape") {
                    setName(item.name);
                    setEditing(false);
                  }
                }}
              />
            ) : (
              <span className="font-medium">{item.name}</span>
            )}
            <Badge
              variant={item.explanation.origin === "ai" ? "accent" : "secondary"}
            >
              {item.explanation.origin === "ai" ? "AI customization" : "Industry pack"}
            </Badge>
            {item.meta ? (
              <span className="text-xs text-muted-foreground">{item.meta}</span>
            ) : null}
          </div>
          <dl className="mt-2 space-y-1 text-sm">
            <ExplRow label="Why" value={item.explanation.why} />
            <ExplRow label="Answers" value={item.explanation.businessQuestion} />
            <ExplRow label="Triggered by" value={item.explanation.causedBy} />
          </dl>
        </div>
        <div className="flex shrink-0 gap-1">
          {renamable ? (
            <Button
              variant="ghost"
              size="sm"
              disabled={pending}
              onClick={() => setEditing((v) => !v)}
            >
              {editing ? "Cancel" : "Rename"}
            </Button>
          ) : null}
          <Button
            variant="ghost"
            size="sm"
            disabled={pending}
            onClick={() => run(() => removeRecommendationItem(orgId, category, item.key))}
          >
            Remove
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

function ExplRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex gap-2">
      <dt className="w-24 shrink-0 text-xs uppercase tracking-wide text-muted-foreground">
        {label}
      </dt>
      <dd className="text-muted-foreground">{value}</dd>
    </div>
  );
}
