import type { IndustryPackDef } from "./types";
import { commonFields, expl, rel, rt } from "./common";

export const constructionPack: IndustryPackDef = {
  key: "construction",
  version: "1.0.0",
  name: "Construction",
  description:
    "For general contractors and builders: projects, sites, phases, subcontractors, RFIs, submittals, inspections, change orders, and the money that flows through them.",
  primaryUnitTypeKey: "project",
  recordTypes: [
    rt("client", "Client", "The owner or developer commissioning the work.", {
      icon: "briefcase", color: "#0891b2", sensitivity: "INTERNAL",
      fields: [commonFields.email(), commonFields.notes()],
      why: "Clients commission projects and approve change orders.",
      question: "Who are we building for?",
      cause: "Clients were named as participants.",
    }),
    rt("project", "Project", "A construction job from lead to closeout.", {
      icon: "hard-hat", color: "#059669",
      fields: [commonFields.status(["Lead", "Estimating", "Contracted", "Active", "Closeout"]), commonFields.dueDate(), commonFields.amount("Contract value")],
      why: "The project is the primary unit of construction work.",
      question: "What jobs are underway and where do they stand?",
      cause: "Projects are the primary unit of work.",
    }),
    rt("site", "Site", "A physical job site.", {
      icon: "map-pin", color: "#65a30d",
      fields: [{ key: "address", name: "Address", type: "short_text" }],
      why: "Sites anchor inspections, phases, and crews to a place.",
      question: "Where is the work happening?",
      cause: "Locations matter to field work.",
    }),
    rt("phase", "Phase", "A stage of a project such as foundation or framing.", {
      icon: "layers", color: "#16a34a",
      fields: [commonFields.status(["Not started", "In progress", "Complete"]), commonFields.dueDate()],
      why: "Phases break a project into schedulable, ownable chunks.",
      question: "What phase are we in and what is next?",
      cause: "Work passes through stages.",
    }),
    rt("employee", "Employee", "Internal staff and field crew.", {
      icon: "user", color: "#2563eb", sensitivity: "INTERNAL",
      fields: [{ key: "role", name: "Role", type: "short_text" }, commonFields.email()],
      why: "Employees own phases and coordinate subs.",
      question: "Who on our team is responsible?",
      cause: "Employees were named as participants.",
    }),
    rt("subcontractor", "Subcontractor", "An external trade contractor.", {
      icon: "truck", color: "#ca8a04",
      fields: [{ key: "trade", name: "Trade", type: "short_text" }, commonFields.email()],
      why: "Subs perform much of the work and carry schedule risk.",
      question: "Which trades are on this job?",
      cause: "Contractors were named as participants.",
    }),
    rt("drawing", "Drawing", "A plan set or drawing revision.", {
      icon: "ruler", color: "#4b5563",
      fields: [{ key: "revision", name: "Revision", type: "short_text" }, { key: "url", name: "Link", type: "url" }],
      why: "Drawings are the source of truth RFIs and submittals reference.",
      question: "What is the current drawing set?",
      cause: "Documents live across systems.",
    }),
    rt("rfi", "RFI", "A request for information.", {
      icon: "help-circle", color: "#d97706",
      fields: [commonFields.status(["Open", "Answered", "Closed"]), commonFields.dueDate()],
      why: "Unanswered RFIs stall field work and shift schedules.",
      question: "What questions are blocking the field?",
      cause: "Blockers were flagged as a risk.",
    }),
    rt("submittal", "Submittal", "A material or product submittal for approval.", {
      icon: "clipboard-check", color: "#0d9488",
      fields: [commonFields.status(["Submitted", "Under review", "Approved", "Rejected"]), commonFields.dueDate()],
      why: "Submittals gate procurement and installation.",
      question: "What is awaiting approval to proceed?",
      cause: "Work requires approvals.",
    }),
    rt("inspection", "Inspection", "A code or quality inspection.", {
      icon: "search", color: "#9333ea",
      fields: [{ key: "date", name: "Date", type: "date" }, commonFields.status(["Scheduled", "Passed", "Failed"])],
      why: "Inspections are compliance gates with real consequences.",
      question: "What inspections are due or failed?",
      cause: "Regulated/quality checkpoints exist.",
    }),
    rt("change_order", "Change order", "A scope or cost change.", {
      icon: "file-diff", color: "#be123c", sensitivity: "CONFIDENTIAL",
      fields: [commonFields.amount("Change amount"), commonFields.status(["Proposed", "Approved", "Rejected"])],
      why: "Change orders drive cost and margin; they need approvals and a trail.",
      question: "How has scope and cost changed?",
      cause: "Financial relationships and approvals.",
    }),
    rt("contract", "Contract", "A prime or subcontract agreement.", {
      icon: "file-signature", color: "#7c3aed", sensitivity: "CONFIDENTIAL",
      fields: [{ key: "effective_date", name: "Effective date", type: "date" }, { key: "expires_on", name: "Expires on", type: "date" }, commonFields.amount("Contract value")],
      why: "Contracts define obligations, retainage, and expirations.",
      question: "What are we committed to and until when?",
      cause: "Contracts must be tracked.",
    }),
    rt("invoice", "Invoice", "A pay application or invoice.", {
      icon: "receipt", color: "#059669", sensitivity: "CONFIDENTIAL",
      fields: [commonFields.amount(), commonFields.status(["Draft", "Submitted", "Paid"]), commonFields.dueDate()],
      why: "Billing ties field progress to cash flow.",
      question: "What has been billed and paid?",
      cause: "Financial relationships in scope.",
    }),
    rt("decision", "Decision", "A recorded project decision.", {
      icon: "gavel", color: "#4b5563",
      fields: [commonFields.notes()],
      why: "Field decisions with sources reduce disputes.",
      question: "Why did we do it this way?",
      cause: "Auditability is a product principle.",
    }),
  ],
  relationshipTypes: [
    rel("project_for_client", "project", "client", "is for", "commissioned", "many_to_one"),
    rel("project_at_site", "project", "site", "is at", "hosts", "many_to_one"),
    rel("phase_of_project", "phase", "project", "is a phase of", "has phase", "many_to_one"),
    rel("employee_manages_phase", "employee", "phase", "manages", "is managed by", "one_to_many"),
    rel("subcontractor_on_phase", "subcontractor", "phase", "works on", "has sub"),
    rel("rfi_references_drawing", "rfi", "drawing", "references", "referenced by"),
    rel("submittal_for_project", "submittal", "project", "is for", "has submittal", "many_to_one"),
    rel("inspection_of_phase", "inspection", "phase", "inspects", "was inspected"),
    rel("change_order_on_project", "change_order", "project", "changes", "has change order", "many_to_one", "CONFIDENTIAL"),
    rel("contract_with_subcontractor", "contract", "subcontractor", "is with", "has contract", "many_to_one", "CONFIDENTIAL"),
    rel("invoice_for_project", "invoice", "project", "bills", "is billed", "many_to_one", "CONFIDENTIAL"),
  ],
  workflows: [
    {
      key: "project_lifecycle",
      name: "Project lifecycle",
      recordTypeKey: "project",
      states: [
        { key: "lead", name: "Lead" },
        { key: "estimating", name: "Estimating" },
        { key: "contracted", name: "Contracted" },
        { key: "mobilization", name: "Mobilization" },
        { key: "active", name: "Active" },
        { key: "closeout", name: "Closeout" },
        { key: "archived", name: "Archived", isTerminal: true },
      ],
      transitions: [
        { from: "lead", to: "estimating" },
        { from: "estimating", to: "contracted", requiresApproval: true },
        { from: "contracted", to: "mobilization" },
        { from: "mobilization", to: "active" },
        { from: "active", to: "closeout" },
        { from: "closeout", to: "archived", requiresApproval: true },
      ],
      explanation: expl(
        "The canonical GC lifecycle from lead through closeout.",
        "Where is each job in its lifecycle?",
        "You described work passing through stages with owners and approvals.",
      ),
    },
  ],
  questions: [
    { id: "open_rfis", text: "Which RFIs are still open?" },
    { id: "failed_inspections", text: "What inspections have failed?" },
    { id: "pending_change_orders", text: "Which change orders are awaiting approval?" },
  ],
  importMappings: [
    { key: "subs_csv", label: "Subcontractors (CSV)", targetRecordTypeKey: "subcontractor", columns: { Name: "displayName", Trade: "trade", Email: "email" } },
    { key: "projects_csv", label: "Projects (CSV)", targetRecordTypeKey: "project", columns: { Name: "displayName", Status: "status" } },
  ],
};
