import type { IndustryPackDef } from "./types";
import { commonFields, expl, rel, rt } from "./common";

export const publishingPack: IndustryPackDef = {
  key: "publishing",
  version: "1.0.0",
  name: "Publishing",
  description:
    "For publishers and imprints: authors, titles, manuscripts, editions, rights, and the editorial pipeline that moves a book from idea to release.",
  primaryUnitTypeKey: "title",
  recordTypes: [
    rt("author", "Author", "A writer or creator under contract.", {
      icon: "pen-tool",
      color: "#2563eb",
      sensitivity: "INTERNAL",
      fields: [commonFields.email(), commonFields.notes()],
      why: "Authors are the source of every title and the party to rights and royalties.",
      question: "Who writes for us and what are they working on?",
      cause: "Publishing revolves around authors.",
    }),
    rt("title", "Title", "A book or publication project.", {
      icon: "book",
      color: "#059669",
      fields: [commonFields.status(["Acquired", "In edit", "Production", "Published"]), commonFields.dueDate()],
      why: "The title is the primary unit of publishing work.",
      question: "What are we publishing and where does it stand?",
      cause: "Titles are the primary unit of work.",
    }),
    rt("imprint", "Imprint", "A publishing brand or line.", {
      icon: "bookmark",
      color: "#7c3aed",
      why: "Imprints group titles under a brand identity and P&L.",
      question: "Which brand does this title belong to?",
      cause: "Publishers operate multiple imprints.",
    }),
    rt("editor", "Editor", "An editor responsible for titles.", {
      icon: "user-check",
      color: "#0891b2",
      sensitivity: "INTERNAL",
      fields: [commonFields.email()],
      why: "Editors own the quality and schedule of titles.",
      question: "Who is responsible for this title editorially?",
      cause: "Editorial ownership is core.",
    }),
    rt("manuscript", "Manuscript", "A draft submission under review.", {
      icon: "file-text",
      color: "#4b5563",
      fields: [commonFields.status(["Submitted", "In review", "Accepted", "Rejected"]), commonFields.dueDate()],
      why: "Manuscripts track the raw material before it becomes a title.",
      question: "What is in the editorial pipeline?",
      cause: "Manuscripts flow through review stages.",
    }),
    rt("edition", "Edition", "A specific published edition or format.", {
      icon: "layers",
      color: "#16a34a",
      fields: [{ key: "format", name: "Format", type: "single_select", options: ["Hardcover", "Paperback", "Ebook", "Audio"] }],
      why: "Editions capture the formats a title ships in.",
      question: "In what formats does this title exist?",
      cause: "Titles ship in multiple editions.",
    }),
    rt("rights", "Rights", "Territorial, translation, or subsidiary rights.", {
      icon: "globe",
      color: "#d97706",
      sensitivity: "CONFIDENTIAL",
      fields: [{ key: "territory", name: "Territory", type: "short_text" }, commonFields.notes()],
      why: "Rights are valuable, contractual, and easy to lose track of.",
      question: "What rights have we granted or retained?",
      cause: "Rights management is central to publishing revenue.",
    }),
    rt("deliverable", "Deliverable", "A produced output such as a cover or layout.", {
      icon: "package",
      color: "#65a30d",
      fields: [commonFields.status(["Pending", "In progress", "Delivered"]), commonFields.dueDate()],
      why: "Deliverables are the concrete outputs production must complete.",
      question: "What outputs are due for this title?",
      cause: "Production produces documents and assets.",
    }),
    rt("vendor", "Vendor", "A printer, designer, or freelancer.", {
      icon: "truck",
      color: "#ca8a04",
      fields: [commonFields.email()],
      why: "External production partners are dependencies with deadlines.",
      question: "Who do we rely on to produce a title?",
      cause: "Vendors were named as participants.",
    }),
    rt("contract", "Contract", "An author or vendor agreement.", {
      icon: "file-signature",
      color: "#be123c",
      sensitivity: "CONFIDENTIAL",
      fields: [{ key: "effective_date", name: "Effective date", type: "date" }, { key: "expires_on", name: "Expires on", type: "date" }, commonFields.amount("Advance / value")],
      why: "Contracts carry advances, royalties, and expirations.",
      question: "What are we committed to and until when?",
      cause: "Contracts and obligations must be tracked.",
    }),
    rt("decision", "Decision", "A recorded editorial or business decision.", {
      icon: "gavel",
      color: "#9333ea",
      fields: [commonFields.notes()],
      why: "Editorial decisions with sources keep the record defensible.",
      question: "Why did we make this call?",
      cause: "Auditability is a product principle.",
    }),
  ],
  relationshipTypes: [
    rel("author_writes_title", "author", "title", "writes", "is written by"),
    rel("title_in_imprint", "title", "imprint", "is published under", "publishes", "many_to_one"),
    rel("editor_owns_title", "editor", "title", "edits", "is edited by", "one_to_many"),
    rel("manuscript_for_title", "manuscript", "title", "is a draft of", "has draft", "many_to_one"),
    rel("edition_of_title", "edition", "title", "is an edition of", "has edition", "many_to_one"),
    rel("rights_for_title", "rights", "title", "cover", "has rights", "one_to_many", "CONFIDENTIAL"),
    rel("deliverable_for_title", "deliverable", "title", "is for", "has deliverable", "many_to_one"),
    rel("vendor_produces_deliverable", "vendor", "deliverable", "produces", "produced by"),
    rel("contract_with_author", "contract", "author", "is with", "has contract", "many_to_one", "CONFIDENTIAL"),
    rel("decision_about_title", "decision", "title", "concerns", "has decision"),
  ],
  workflows: [
    {
      key: "editorial_pipeline",
      name: "Editorial pipeline",
      recordTypeKey: "title",
      states: [
        { key: "acquired", name: "Acquired" },
        { key: "in_edit", name: "In edit" },
        { key: "production", name: "Production" },
        { key: "published", name: "Published", isTerminal: true },
      ],
      transitions: [
        { from: "acquired", to: "in_edit" },
        { from: "in_edit", to: "production", requiresApproval: true },
        { from: "production", to: "published", requiresApproval: true },
      ],
      explanation: expl(
        "Mirrors how a title moves from acquisition to shelf.",
        "Where is each title in the publishing process?",
        "You described work passing through stages with approvals.",
      ),
    },
  ],
  questions: [
    { id: "titles_by_author", text: "What titles is this author working on?" },
    { id: "rights_expiring", text: "Which rights or contracts expire soon?" },
  ],
  importMappings: [
    { key: "authors_csv", label: "Authors (CSV)", targetRecordTypeKey: "author", columns: { Name: "displayName", Email: "email" } },
    { key: "titles_csv", label: "Titles (CSV)", targetRecordTypeKey: "title", columns: { Title: "displayName", Status: "status" } },
  ],
};
