import type { IndustryPackDef } from "./types";
import { commonFields, expl, rel, rt } from "./common";

export const softwarePack: IndustryPackDef = {
  key: "software",
  version: "1.0.0",
  name: "Software development",
  description:
    "For software teams: customers, products, repositories, services, features, tickets, sprints, releases, deployments, incidents, and the controls around them.",
  primaryUnitTypeKey: "feature",
  recordTypes: [
    rt("person", "Person", "A teammate, founder, investor, or advisor.", {
      icon: "user", color: "#0ea5e9", sensitivity: "INTERNAL",
      fields: [
        commonFields.email(),
        {
          key: "role",
          name: "Role",
          type: "single_select",
          options: [
            "Founder",
            "Engineer",
            "Engineering lead",
            "Product manager",
            "Designer",
            "Investor",
            "Advisor",
          ],
        },
        commonFields.notes(),
      ],
      why: "People own work, run services, and back the company — without them the graph has no accountability.",
      question: "Who owns this, who reports to whom, and who is backing us?",
      cause: "Employees, contractors, and investors were named as participants.",
    }),
    rt("vendor", "Provider / subscription", "A SaaS tool or provider you pay for: hosting, email, dev tools, payments, etc.", {
      icon: "plug", color: "#6366f1", sensitivity: "INTERNAL",
      fields: [
        {
          key: "category",
          name: "Category",
          type: "single_select",
          options: [
            "Hosting",
            "Email",
            "Payments",
            "Dev tools",
            "Analytics",
            "Auth",
            "Monitoring",
            "Comms",
            "Design",
            "Productivity",
            "Domain",
            "Other",
          ],
        },
        { key: "cost", name: "Monthly cost", type: "currency", sensitivity: "CONFIDENTIAL" },
        {
          key: "cycle",
          name: "Billing cycle",
          type: "single_select",
          options: ["Monthly", "Annual", "Usage-based"],
        },
        { key: "url", name: "URL", type: "url" },
        commonFields.status(["Active", "Trial", "Cancelled"]),
      ],
      why: "The SaaS tools and infrastructure you subscribe to are real dependencies and real spend; making them first-class shows what powers each app and what it costs.",
      question: "What do we subscribe to, what does it power, and what does it cost?",
      cause: "You described subscriptions and providers (e.g. Google Workspace, Cursor, Resend, Vercel).",
    }),
    rt("customer", "Customer", "A paying customer or account.", {
      icon: "briefcase", color: "#0891b2", sensitivity: "INTERNAL",
      fields: [commonFields.email(), commonFields.notes()],
      why: "Customers ground features and incidents in real impact.",
      question: "Who is affected by this work or outage?",
      cause: "Customers were named as participants.",
    }),
    rt("product", "Product", "A product or product line.", {
      icon: "box", color: "#7c3aed",
      why: "Products group features, services, and releases.",
      question: "Which product does this belong to?",
      cause: "Work is organized by product.",
    }),
    rt("repository", "Repository", "A source code repository.", {
      icon: "git-branch", color: "#4b5563",
      fields: [{ key: "url", name: "URL", type: "url" }],
      why: "Repositories are where features and fixes actually land.",
      question: "Where does the code for this live?",
      cause: "GitHub / source control was selected.",
    }),
    rt("service", "Service", "A deployable service or component.", {
      icon: "server", color: "#16a34a",
      fields: [commonFields.status(["Healthy", "Degraded", "Down"]) ],
      why: "Services are what incidents affect and deployments target.",
      question: "What runs in production and how healthy is it?",
      cause: "Operations track services.",
    }),
    rt("environment", "Environment", "A deployment environment (dev/stage/prod).", {
      icon: "layers", color: "#65a30d",
      fields: [{ key: "kind", name: "Kind", type: "single_select", options: ["dev", "staging", "production"] }],
      why: "Environments scope deployments and access.",
      question: "Where is this deployed?",
      cause: "Delivery flows across environments.",
    }),
    rt("requirement", "Requirement", "A product requirement or spec.", {
      icon: "list-checks", color: "#d97706",
      fields: [commonFields.notes()],
      why: "Requirements connect customer need to delivered features.",
      question: "What are we supposed to build and why?",
      cause: "Work starts from requirements.",
    }),
    rt("feature", "Feature", "A unit of product work being delivered.", {
      icon: "sparkles", color: "#059669",
      fields: [commonFields.status(["Proposed", "Planned", "In development", "Review", "Released"]), commonFields.dueDate()],
      why: "The feature is the primary unit of delivery.",
      question: "What are we shipping and where does it stand?",
      cause: "Features are the primary unit of work.",
    }),
    rt("ticket", "Ticket", "A bug or task.", {
      icon: "bug", color: "#be123c",
      fields: [commonFields.status(["Open", "In progress", "Closed"]), commonFields.dueDate()],
      why: "Tickets track the granular work and defects.",
      question: "What issues are open?",
      cause: "Work breaks into tickets.",
    }),
    rt("sprint", "Sprint", "A time-boxed iteration.", {
      icon: "timer", color: "#9333ea",
      fields: [{ key: "start", name: "Start", type: "date" }, { key: "end", name: "End", type: "date" }],
      why: "Sprints organize delivery cadence and commitment.",
      question: "What are we committing to this iteration?",
      cause: "Delivery is time-boxed.",
    }),
    rt("release", "Release", "A shipped version.", {
      icon: "tag", color: "#0d9488",
      fields: [{ key: "version", name: "Version", type: "short_text" }, { key: "date", name: "Date", type: "date" }],
      why: "Releases bundle features and mark what customers receive.",
      question: "What went out and when?",
      cause: "Outputs are released to customers.",
    }),
    rt("deployment", "Deployment", "A deploy of a release to an environment.", {
      icon: "rocket", color: "#2563eb",
      fields: [commonFields.status(["Pending", "Deployed", "Rolled back"]), { key: "at", name: "Deployed at", type: "datetime" }],
      why: "Deployments are the events that change production.",
      question: "What changed in production and when?",
      cause: "Delivery ends in deployment.",
    }),
    rt("incident", "Incident", "A production incident or outage.", {
      icon: "alert-triangle", color: "#dc2626", sensitivity: "INTERNAL",
      fields: [commonFields.status(["Investigating", "Identified", "Resolved"]), { key: "severity", name: "Severity", type: "single_select", options: ["SEV1", "SEV2", "SEV3"] }],
      why: "Incidents connect services, deployments, and customer impact.",
      question: "What broke, what caused it, and who was affected?",
      cause: "Blockers and failures were flagged as risks.",
    }),
    rt("decision", "Decision", "An architecture or product decision (ADR).", {
      icon: "gavel", color: "#4b5563",
      fields: [commonFields.notes()],
      why: "Decisions with sources make architecture defensible over time.",
      question: "Why did we build it this way?",
      cause: "Auditability is a product principle.",
    }),
    rt("subscription", "Subscription", "A customer's subscription/plan.", {
      icon: "credit-card", color: "#16a34a", sensitivity: "CONFIDENTIAL",
      fields: [commonFields.amount("MRR"), commonFields.status(["Trial", "Active", "Churned"]) ],
      why: "Subscriptions tie product work to revenue.",
      question: "What is each customer paying?",
      cause: "Financial relationships in scope.",
    }),
    rt("security_control", "Security control", "A control safeguarding the system.", {
      icon: "shield-check", color: "#7c3aed", sensitivity: "RESTRICTED",
      fields: [{ key: "framework", name: "Framework", type: "short_text" }, commonFields.status(["Implemented", "Partial", "Missing"]) ],
      why: "Controls make security posture explicit and auditable.",
      question: "Are our safeguards in place?",
      cause: "Regulated / sensitive information may be involved.",
    }),
  ],
  relationshipTypes: [
    rel("person_owns_feature", "person", "feature", "owns", "is owned by", "one_to_many"),
    rel("person_operates_service", "person", "service", "operates", "is operated by", "one_to_many"),
    rel("person_reports_to", "person", "person", "reports to", "manages", "many_to_one"),
    rel("person_member_of_product", "person", "product", "works on", "has team member", "many_to_many"),
    rel("investor_backs_product", "person", "product", "invests in", "is backed by", "many_to_many"),
    rel("service_hosted_on_vendor", "service", "vendor", "is hosted on", "hosts", "many_to_one"),
    rel("service_monitored_by_vendor", "service", "vendor", "is monitored by", "monitors", "many_to_many"),
    rel("repository_hosted_on_vendor", "repository", "vendor", "is hosted on", "hosts", "many_to_many"),
    rel("product_has_repository", "product", "repository", "has repository", "belongs to product", "one_to_many"),
    rel("product_uses_vendor", "product", "vendor", "uses", "is used by", "many_to_many"),
    rel("person_uses_vendor", "person", "vendor", "uses", "is used by", "many_to_many"),
    // Lets a deployable service hang off the product it powers (so attaching
    // "github" / "api" from a product never floats unlinked).
    rel("service_supports_product", "service", "product", "supports", "is supported by", "many_to_many"),
    rel("customer_client_of_product", "customer", "product", "is client of", "built for", "one_to_many"),
    rel("feature_belongs_to_product", "feature", "product", "belongs to", "has feature", "many_to_one"),
    rel("feature_depends_on_feature", "feature", "feature", "depends on", "is required by", "many_to_many"),
    rel("feature_in_service", "feature", "service", "runs in", "contains", "many_to_one"),
    rel("feature_implements_requirement", "feature", "requirement", "implements", "is implemented by"),
    rel("ticket_part_of_feature", "ticket", "feature", "is part of", "has ticket", "many_to_one"),
    rel("feature_in_sprint", "feature", "sprint", "is in", "contains", "many_to_one"),
    rel("feature_in_release", "feature", "release", "ships in", "includes", "many_to_one"),
    rel("release_deployed_via", "release", "deployment", "is deployed via", "deploys", "one_to_many"),
    rel("deployment_to_environment", "deployment", "environment", "targets", "receives", "many_to_one"),
    rel("incident_affects_service", "incident", "service", "affects", "was affected in"),
    rel("service_in_repository", "service", "repository", "is built from", "builds", "many_to_one"),
    rel("subscription_for_customer", "subscription", "customer", "bills", "has subscription", "one_to_one", "CONFIDENTIAL"),
    rel("control_protects_service", "security_control", "service", "protects", "is protected by", "many_to_many", "RESTRICTED"),
  ],
  workflows: [
    {
      key: "delivery_flow",
      name: "Feature delivery",
      recordTypeKey: "feature",
      states: [
        { key: "proposed", name: "Proposed" },
        { key: "planned", name: "Planned" },
        { key: "in_development", name: "In development" },
        { key: "review", name: "Review" },
        { key: "released", name: "Released", isTerminal: true },
      ],
      transitions: [
        { from: "proposed", to: "planned" },
        { from: "planned", to: "in_development" },
        { from: "in_development", to: "review" },
        { from: "review", to: "released", requiresApproval: true },
      ],
      explanation: expl(
        "The standard path a feature takes from idea to production.",
        "Where is each feature in delivery?",
        "You described work passing through stages with review.",
      ),
    },
  ],
  questions: [
    { id: "open_incidents", text: "Which incidents are unresolved?" },
    { id: "features_in_release", text: "What features shipped in the last release?" },
    { id: "unowned_features", text: "Which features have no owner?" },
    { id: "who_owns_service", text: "Who operates each production service?" },
    { id: "hosting_dependencies", text: "Which providers is each service hosted on?" },
    { id: "who_backs_us", text: "Who invests in this product?" },
  ],
  importMappings: [
    { key: "customers_csv", label: "Customers (CSV)", targetRecordTypeKey: "customer", columns: { Name: "displayName", Email: "email" } },
    { key: "features_csv", label: "Features (CSV)", targetRecordTypeKey: "feature", columns: { Name: "displayName", Status: "status" } },
  ],
};
